spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signer-key: TgMxWZMF1rIthXYHeUecZBO/m9cTidH3UiBh8h+zjQvTAKwWe30OOAupH9VsssDU
  expiration: 86400000

# Simple logging configuration
logging:
  level:
    com.dungnb.be: INFO
